employeeProyect/applications/departamento/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = "departamento_app"

urlpatterns = [
    path('list-departamento/', views.ListAllDepartamentos.as_view(),
         name='list_departamentos'),
    path('create-department/', views.DepartamentoCreateView.as_view(),
         name='nuevo_departamento')
]

employeeProyect/applications/persona/urls.py
from django import views
from django.contrib import admin
from django.urls import path

from . import views

app_name = "persona_app"

urlpatterns = [
    path('lista/', views.ListAllEmpleados.as_view(), name='employee_all'),
    path('list-admin/', views.ListAllEmpleadosAdmin.as_view(),
         name='employee_all_admin'),
    path('list-by-area/<shortname>',
         views.ListByArea.as_view(), name='employees_by_area'),
    path('list-by-skill/', views.ListBySkill.as_view(), name='employees_by_skill'),
    path('list-by-job/<job>', views.ListByJob.as_view(), name='employees_by_job'),
    path('find-employee', views.ListByKword.as_view(), name='employees_by_kword'),
    path('detail-employee/<pk>', views.EmpleadoDetailView.as_view(),
         name='detail_employee'),
    path('create-employee/', views.EmpleadoCreateView.as_view(),
         name='create_employee'),
    path('create-skill/', views.SkillCreateView.as_view(), name='create_skill'),
    path('success/', views.SuccessView.as_view(), name='success'),
    path('update-employee/<pk>/', views.EmpleadoUpdateView.as_view(),
         name='modificar_empleado'),
    path('delete-employee/<pk>/', views.EmpleadoDeleteView.as_view(),
         name='eliminar_empleado'),
]

employeeProyect/employeeProyect/urls.py
from django.contrib import admin
from django.urls import path,re_path,include
from django.conf import settings
from django.conf.urls.static import static
from applications.persona.views import HomeView
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',  HomeView.as_view(), name = 'home'),
    # incluimos las urls de la app departamento
    re_path('departamento/', include('applications.departamento.urls')),
    re_path('persona/', include('applications.persona.urls')),
    re_path('home/', include('applications.home.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

employeeProyect/templates/includes/header.html
<div class="top-bar">
  <div class="top-bar-left">
    <ul class="dropdown menu" data-dropdown-menu>
      <li class="menu-text">Empleados</li>
      <li><a href="{% url 'persona_app:employee_all' %}">Listar Empleados</a></li>
      <li><a href="{% url 'departamento_app:list_departamentos' %}">Departamentos</a></li>
      <li><a href="{% url 'persona_app:employee_all_admin' %}">Administrar Empleados</a></li>
      <li><a href="{% url 'departamento_app:nuevo_departamento' %}">Nuevo departamento</a></li>
    </ul>
  </div>
  <div class="top-bar-right">
    <ul class="menu">
      <li><input type="search" placeholder="Buscar empleado" /></li>
      <li><a href="{% url 'persona_app:create_employee' %}" class="button">Registrar nuevo empleado</a></li>
    </ul>
  </div>
</div>