employeeProyect/applications/persona/urls.py
from django import views
from django.contrib import admin
from django.urls import path

from . import views

app_name = "persona_app"

urlpatterns = [
    path('lista/', views.ListAllEmpleados.as_view(), name='employee_all'),
    path('list-admin/', views.ListAllEmpleadosAdmin.as_view(),
         name='employee_all_admin'),
    path('list-by-area/<shortname>',
         views.ListByArea.as_view(), name='employees_by_area'),
    path('list-by-skill/', views.ListBySkill.as_view(), name='employees_by_skill'),
    path('list-by-job/<job>', views.ListByJob.as_view(), name='employees_by_job'),
    path('find-employee', views.ListByKword.as_view(), name='employees_by_kword'),
    path('detail-employee/<pk>', views.EmpleadoDetailView.as_view(),
         name='detail_employee'),
    path('create-employee/', views.EmpleadoCreateView.as_view(),
         name='create_employee'),
    path('create-skill/', views.SkillCreateView.as_view(), name='create_skill'),
    path('success/', views.SuccessView.as_view(), name='success'),
    path('update-employee/<pk>/', views.EmpleadoUpdateView.as_view(),
         name='modificar_empleado'),
    path('delete-employee/<pk>/', views.EmpleadoDeleteView.as_view(),
         name='eliminar_empleado'),
]

employeeProyect/employeeProyect/urls.py
from django.contrib import admin
from django.urls import path,re_path,include
from django.conf import settings
from django.conf.urls.static import static
from applications.persona.views import HomeView
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',  HomeView.as_view(), name = 'home'),
    # incluimos las urls de la app departamento
    re_path('departamento/', include('applications.departamento.urls')),
    re_path('persona/', include('applications.persona.urls')),
    re_path('home/', include('applications.home.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

employeeProyect/applications/persona/models.py
from django.db import models
from django.forms import CharField
from applications.departamento.models import Departamento
from ckeditor.fields import RichTextField

# Create your models here.

class Skills(models.Model):
    skill = models.CharField('Habilidad', max_length=50)

    class meta:
        verbose_name = 'Habilidad'
        verbose_name_prural = 'Habilidades Empleados'
    
    def __str__(self):
        return str(self.id) + '-' + self.skill

class Empleado(models.Model):

    JOB_CHOICES = (
    ('0', 'CONTADOR'),
    ('1', 'ADMINISTRADOR'),
    ('2', 'ECONOMISTA'),
    ('23', 'OTRO'),
    )

    first_name = models.CharField('Nombres', max_length=50)
    last_name = models.CharField('Apellidos', max_length=50)
    full_name = models.CharField('Nombre completo', max_length=120, blank=True)
    job = models.CharField('Trabajo',choices=JOB_CHOICES, max_length=50)
    departamento = models.ForeignKey(Departamento, verbose_name="Departamento del empleado", on_delete=models.CASCADE)
    avatar = models.ImageField(upload_to='empleado', blank = True, null = True)
    skills  = models.ManyToManyField(Skills)
    cv = RichTextField()

    class Meta:
        verbose_name = "Mi empleado"
        verbose_name_plural = "Empleados de la empresa"
        ordering = ['first_name']
        unique_together = ('first_name', 'departamento')

    def __str__(self):
        return str(self.id) + '-' + self.first_name + '-' + self.last_name

employeeProyect/applications/persona/forms.py
import imp
from tkinter import Widget
from django import forms

from .models import Empleado

class EmpleadoForm(forms.ModelForm):

    class Meta:
        model = Empleado
        fields = (
            'first_name', 
            'last_name', 
            'job', 
            'departamento', 
            'skills',
            'avatar'
        )
        widgets = {
            'first_name' : forms.TextInput(
                attrs= {
                    'placeholder' : 'Nombres'
                }
            ),
            'skills' : forms.CheckboxSelectMultiple()
        }

    def clean_first_name(self):
        first_name = self.cleaned_data.get('first_name')
        
        if first_name.isdigit():
            raise forms.ValidationError('Solo se permiten letras')
        
        return first_name

employeeProyect/applications/persona/views.py
from django.urls import reverse_lazy
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    TemplateView,
    UpdateView,
    DeleteView
)
from .models import Empleado, Skills
from .forms import EmpleadoForm

class HomeView(TemplateView):
    template_name = 'home.html'

class ListAllEmpleados(ListView):
    template_name = 'persona/list_all.html'
    paginate_by = 4
    ordering = 'first_name'

    context_object_name = 'empleados'

    def get_queryset(self):
        kword = self.request.GET.get('kword', '')
        print(kword)
        lista = Empleado.objects.filter(
            first_name__icontains=kword
        )
        return lista

class ListByArea(ListView):
    template_name = 'persona/list_by_area.html'
    def get_queryset(self):
        area = self.kwargs['shortname']
        
        lista = Empleado.objects.filter(
            departamento__short_name=area
        )
        return lista
    
    def get_context_data(self, **kwargs):
        area = self.kwargs['shortname']
        context = super(ListByArea, self).get_context_data(**kwargs)
        context['area'] = area
        return context

class ListByKword(ListView):
    template_name = 'persona/list_by_kword.html'

    context_object_name = 'empleados'
    
    def get_queryset(self):
        kword = self.request.GET.get('kword', '')
        print(kword)
        lista = Empleado.objects.filter(
            first_name__contains=kword
        )
        return lista

class ListBySkill(ListView):
    template_name = 'persona/list_by_skill.html'
    context_object_name = 'skills'

    def get_queryset(self):
        empleado = Empleado.objects.get(id='1')
        skills = empleado.skills.all()
        return skills

class ListByJob(ListView):
    template_name = 'persona/list_by_job.html'

    def get_queryset(self):
        job = self.kwargs['job']

        lista = Empleado.objects.filter(
            job = job
        )
        return lista

class EmpleadoDetailView(DetailView):
    model = Empleado
    template_name = "persona/detail_empleado.html"

    def get_context_data(self, **kwargs):
        context = super(EmpleadoDetailView, self).get_context_data(**kwargs)
        context['titulo'] = 'Empleado del mes'
        return context

class SuccessView(TemplateView):
    template_name = "persona/success.html"
    
class EmpleadoCreateView(CreateView):
    model = Empleado
    form_class = EmpleadoForm
    template_name = "persona/create_empleado.html"
    success_url = reverse_lazy('persona_app:employee_all_admin')

    def form_valid(self, form):
        
        employee = form.save(commit=False)
        employee.full_name = employee.first_name + ' ' + employee.last_name
        employee.save()
        return super(EmpleadoCreateView, self).form_valid(form)

class SkillCreateView(CreateView):
    model = Skills
    fields = ('__all__')
    template_name = "persona/create_skill.html"
    success_url = "."


class EmpleadoUpdateView(UpdateView):
    model = Empleado
    fields = ['first_name', 'last_name', 'job', 'departamento', 'skills']
    template_name = "persona/update.html"

    def get_success_url(self):
          pk=self.kwargs['pk']
          print(id)
          return reverse_lazy('persona_app:employee_all_admin')

    def post(self, request, *args, **kwargs):

        return super().post(request, *args, **kwargs)
    
    def form_valid(self, form):
        
        employee = form.save(commit=False)
        employee.full_name = employee.first_name + ' ' + employee.last_name
        employee.save()
        return super(EmpleadoUpdateView, self).form_valid(form)



class EmpleadoDeleteView(DeleteView):
    model = Empleado
    template_name = "persona/delete.html"
    success_url = reverse_lazy('persona_app:employee_all_admin')


class ListAllEmpleadosAdmin(ListView):
    template_name = 'persona/list_all_admin.html'
    paginate_by = 4
    ordering = 'first_name'
    context_object_name = 'empleados'
    model = Empleado
    

employeeProyect/templates/persona/create_empleado.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
Registrar Empleado
{% endblock title %}

{% block content %}

{% include 'includes/header.html' %}

<div class="grid-container">
    <div class="grid-x">
        <div class="cell">
            <h1>Registrar Empleado</h1>
        </div>
        <div class="cell">
            <form class="grid-x grid-margin-x" method="POST" enctype="multipart/form-data">{% csrf_token %}
                <div class="large-6 cell">
                    <label>Nombres:
                        {{form.first_name}}
                    </label>
                </div>
                <div class="large-6 cell">
                    <label>Apellidos:
                        {{form.last_name}}
                    </label>
                </div>
                <div class="large-6 cell">
                    <label>Trabajo:
                        {{form.job}}
                    </label>
                </div>
                <div class="large-6 cell">
                    <label>Area:
                        {{form.departamento}}
                    </label>
                </div>
                <div class="large-6 cell">
                    <label>Avatar:
                        {{form.avatar}}
                    </label>
                </div>
                <div class="large-6 cell">
                    <label>Habilidades extra:
                        {{form.skills}}
                    </label>
                </div>
                <div class="cell">
                    <button class="submit success button" type="submit">Crear Empleado</button>
                </div>
            </form>
        </div>

    </div>
</div>
{% endblock content %}

employeeProyect/templates/persona/create_skill.html
<h1>Registrar Habilidad</h1>
<form method="POST">{% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Crear Habilidad</button>
</form>

employeeProyect/templates/persona/delete.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
Eliminar Empleado
{% endblock title %}

{% block content %}

{% include 'includes/header.html' %}

<div class="grid-container">
    <div class="grid-x">
        <div class="cell">
            <h1>Eliminar Empleado: {{ object.full_name }}</h1>
        </div>
        <div class="cell">
            <form class="grid-x grid-margin-x" method="POST">{% csrf_token %}
                <div class="large-6 cell">
                    <p>Confirme que desea eliminar</p>
                </div>
                <div class="cell">
                    <button class="alert button" type="submit">Eliminar</button>
                </div>
            </form>
        </div>

    </div>
</div>
{% endblock content %}
</form>

employeeProyect/templates/persona/detail_empleado.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
{{ object.full_name }}
{% endblock title %}

{% block content %}

{% include 'includes/header.html' %}
<div class="grid-container">
    <div class="grid-x grid-margin-x align-center">
        <div class="cell large-4 card" style="width: 300px;">
            <div class="card-divider">
                {{empleado.get_job_display}}
            </div>
            {% if empleado.avatar %}
            <img src="{{ empleado.avatar.url }}">
            {% else %}
            <img src="{% static 'img/no-photo.gif' %}">
            {% endif %}
            <div class="card-section">
                <h4>{{empleado.full_name}}</h4>
                <p>{{empleado.first_name}}</p>
                <p>{{empleado.last_name}}</p>
                <p>{{ empleado.departamento.short_name }}</p>
                <p><span class="label">Habilidades</span></p>
                <ul>
                    {% for skill in empleado.skills.all %}
                        <li>{{skill.skill}}</li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
</div>
{% endblock content %}
<h1>Detalles empleado {{titulo}}</h1>
{{ empleado }}

<h3>Todos los datos</h3>
<p>{{ empleado.first_name }}</p>
<p>{{ empleado.last_name }}</p>
<p>{{ empleado.full_name }}</p>
<p>{{ empleado.get_job_display }}</p>
<p>{{ empleado.departamento }}</p>

employeeProyect/templates/persona/list_all.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
Todos los empleados
{% endblock title %}

{% block content %}
{% include 'includes/header.html' %}
<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Lista Empleados</h1>
        <form class="cell grid-x grid-margin-x" method="GET">{% csrf_token %}
            <div class="cell large-7">
                <input type="text" id="kword" name="kword" placeholder="Buscar empleado">
            </div>
            <div class="cell large-2">
                <button type="submit" class="success button">Save</button>
            </div>
        </form>
        <div class="cell">
            <table>
                <thead>
                    <tr>
                        <th width="200">ID</th>
                        <th width="150">NOMBRES</th>
                        <th width="150">APELLIDOS</th>
                        <th>DEPARTAMENTO</th>
                        <th width="150">ACCION</th>
                    </tr>
                </thead>
                <tbody>
                    {%for empleado in empleados%}
                    <tr>
                        <td>{{empleado.id}}</td>
                        <td>{{empleado.first_name}}</td>
                        <td>{{empleado.last_name}}</td>
                        <td>{{empleado.departamento}}</td>
                        <td><a class="button primary"
                                href="{% url 'persona_app:detail_employee' pk=empleado.id %}">Ver</a></td>
                    </tr>
                    {%endfor%}

                </tbody>
            </table>
        </div>
        <div class="cell">
            {% if is_paginated %}
            <nav aria-label="Pagination">
                <ul class="pagination text-center">
                    {% if page_obj.has_previous %}
                    <li class="pagination-previous"><a href="?page={{ page_obj.previous_page_number }}"
                            aria-label="Previous page">Previous</a>
                    </li>
                    {% endif %}

                    {% for page in paginator.page_range %}

                    {% if page == page_obj.number %}
                    <li class="current"><span class="show-for-sr">You're on page</span><a href="?page={{ page }}"
                            aria-label="Page {{ page }}">{{ page }}</a></li>
                    {% else %}
                    <li><a href="?page={{ page }}" aria-label="Page {{ page }}">{{ page }}</a></li>
                    {% endif %}

                    {% endfor %}

                    {% if page_obj.has_next %}
                    <li class="pagination-next"><a href="?page={{ page_obj.next_page_number }}"
                            aria-label="Next page">Next</a></li>
                    {% endif %}
                </ul>
            </nav>
            {% endif %}
        </div>
    </div>
</div>
{% endblock content %}

employeeProyect/templates/persona/list_all_admin.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
Administrar empleados
{% endblock title %}

{% block content %}
{% include 'includes/header.html' %}
<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Administración de empleados</h1>
        <div class="cell">
            <table>
                <thead>
                    <tr>
                        <th width="50">ID</th>
                        <th width="150">NOMBRES</th>
                        <th width="150">APELLIDOS</th>
                        <th>DEPARTAMENTO</th>
                        <th width="350">ACCION</th>
                    </tr>
                </thead>
                <tbody>
                    {%for empleado in empleados%}
                    <tr>
                        <td>{{empleado.id}}</td>
                        <td>{{empleado.first_name}}</td>
                        <td>{{empleado.last_name}}</td>
                        <td>{{empleado.departamento}}</td>
                        <td><a class="submit success button"
                                href="{% url 'persona_app:modificar_empleado' pk=empleado.id %}">Actualizar</a>
                            <a class="alert button"
                                href="{% url 'persona_app:eliminar_empleado' pk=empleado.id %}">Eliminar</a>
                        </td>
                    </tr>
                    {%endfor%}

                </tbody>
            </table>
        </div>
        <div class="cell">
            {% if is_paginated %}
            <nav aria-label="Pagination">
                <ul class="pagination text-center">
                    {% if page_obj.has_previous %}
                    <li class="pagination-previous"><a href="?page={{ page_obj.previous_page_number }}"
                            aria-label="Previous page">Previous</a>
                    </li>
                    {% endif %}

                    {% for page in paginator.page_range %}

                    {% if page == page_obj.number %}
                    <li class="current"><span class="show-for-sr">You're on page</span><a href="?page={{ page }}"
                            aria-label="Page {{ page }}">{{ page }}</a></li>
                    {% else %}
                    <li><a href="?page={{ page }}" aria-label="Page {{ page }}">{{ page }}</a></li>
                    {% endif %}

                    {% endfor %}

                    {% if page_obj.has_next %}
                    <li class="pagination-next"><a href="?page={{ page_obj.next_page_number }}"
                            aria-label="Next page">Next</a></li>
                    {% endif %}
                </ul>
            </nav>
            {% endif %}
        </div>
    </div>
</div>
{% endblock content %}

employeeProyect/templates/persona/list_by_area.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
Lista de empleados por area
{% endblock title %}

{% block content %}
{% include 'includes/header.html' %}
<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Lista Empleados de {{ area }}</h1>
        <div class="cell">
            <table>
                <thead>
                    <tr>
                        <th width="200">ID</th>
                        <th width="150">NOMBRES</th>
                        <th width="150">APELLIDOS</th>
                        <th>DEPARTAMENTO</th>
                        <th width="150">ACCION</th>
                    </tr>
                </thead>
                <tbody>
                    {%for empleado in object_list%}
                    <tr>
                        <td>{{empleado.id}}</td>
                        <td>{{empleado.first_name}}</td>
                        <td>{{empleado.last_name}}</td>
                        <td>{{empleado.departamento}}</td>
                        <td><a class="button primary"
                                href="{% url 'persona_app:detail_employee' pk=empleado.id %}">Ver</a></td>
                    </tr>
                    {%endfor%}

                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock content %}

employeeProyect/templates/persona/list_by_job.html
<h1>Todos los empleados por trabajo</h1>

<ul>
    {%for empleado in object_list%}
    <li>{{empleado}}</li>
    {%endfor%}
</ul>

employeeProyect/templates/persona/list_by_kword.html
<h1>Buscar empleados por palabra clave</h1>
<form method = "GET">{% csrf_token %}
    <input type="text" id="kword" name="kword" placeholder = "ingrese nombre aqui">
    <button type="submit">Buscar</button>
</form>
<h3>Empleados encontrados</h3>
<ul>
    {%for empleado in empleados%}
    <li>{{empleado}}</li>
    {%endfor%}
</ul>

employeeProyect/templates/persona/list_by_skill.html
<h1>Habilidades de un empleado</h1>

<ul>
    {%for skill in skills%}
    <li>{{skill}}</li>
    {%endfor%}
</ul>

employeeProyect/templates/persona/success.html
<h1>Se guardó correctamente el empleado</h1>

employeeProyect/templates/persona/update.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
Modificar datos empledo
{% endblock title %}

{% block content %}

{% include 'includes/header.html' %}

<div class="grid-container">
    <div class="grid-x">
        <div class="cell">
            <h1>Modificar datos empledo</h1>
        </div>
        <div class="cell">
            <form class="grid-x grid-margin-x" method="POST">{% csrf_token %}
                <div class="large-6 cell">
                    <label>Nombres:
                        {{form.first_name}}
                    </label>
                </div>
                <div class="large-6 cell">
                    <label>Apellidos:
                        {{form.last_name}}
                    </label>
                </div>
                <div class="large-6 cell">
                    <label>Trabajo:
                        {{form.job}}
                    </label>
                </div>
                <div class="large-6 cell">
                    <label>Area:
                        {{form.departamento}}
                    </label>
                </div>
                <div class="large-6 cell">
                    <label>Habilidades extra:
                        {{form.skills}}
                    </label>
                </div>
                <div class="cell">
                    <button class="submit success button" type="submit">Actualizar</button>
                </div>
            </form>
        </div>

    </div>
</div>
{% endblock content %}