employeeProyect/applications/departamento/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = "departamento_app"

urlpatterns = [
    path('list-departamento/', views.ListAllDepartamentos.as_view(),
         name='list_departamentos'),
    path('create-department/', views.DepartamentoCreateView.as_view(),
         name='nuevo_departamento')
]

employeeProyect/applications/persona/urls.py
from django import views
from django.contrib import admin
from django.urls import path

from . import views

app_name = "persona_app"

urlpatterns = [
    path('lista/', views.ListAllEmpleados.as_view(), name='employee_all'),
    path('list-admin/', views.ListAllEmpleadosAdmin.as_view(),
         name='employee_all_admin'),
    path('list-by-area/<shortname>',
         views.ListByArea.as_view(), name='employees_by_area'),
    path('list-by-skill/', views.ListBySkill.as_view(), name='employees_by_skill'),
    path('list-by-job/<job>', views.ListByJob.as_view(), name='employees_by_job'),
    path('find-employee', views.ListByKword.as_view(), name='employees_by_kword'),
    path('detail-employee/<pk>', views.EmpleadoDetailView.as_view(),
         name='detail_employee'),
    path('create-employee/', views.EmpleadoCreateView.as_view(),
         name='create_employee'),
    path('create-skill/', views.SkillCreateView.as_view(), name='create_skill'),
    path('success/', views.SuccessView.as_view(), name='success'),
    path('update-employee/<pk>/', views.EmpleadoUpdateView.as_view(),
         name='modificar_empleado'),
    path('delete-employee/<pk>/', views.EmpleadoDeleteView.as_view(),
         name='eliminar_empleado'),
]

employeeProyect/employeeProyect/urls.py
from django.contrib import admin
from django.urls import path,re_path,include
from django.conf import settings
from django.conf.urls.static import static
from applications.persona.views import HomeView
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',  HomeView.as_view(), name = 'home'),
    # incluimos las urls de la app departamento
    re_path('departamento/', include('applications.departamento.urls')),
    re_path('persona/', include('applications.persona.urls')),
    re_path('home/', include('applications.home.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

employeeProyect/applications/departamento/models.py
from distutils.text_file import TextFile
from re import M
from django.db import models

# Create your models here.
class Departamento(models.Model):
    name = models.CharField("Nombre", max_length=50)
    short_name = models.CharField("Nombre Corto", max_length=50, unique=True)
    anulate = models.BooleanField("Anulado", default=False)

    class Meta:
        verbose_name = "Mi departamento"
        verbose_name_plural = "Areas de la empresa"
        ordering = ['name']
        unique_together = ('name', 'short_name')
    
    def __str__(self):
        return str(self.id) + '-' + self.name + '-' + self.short_name

employeeProyect/applications/departamento/forms.py
from django import forms

from .models import Departamento

class DepartamentoForm(forms.Form):

    nombre = forms.CharField(max_length=50)
    apellidos = forms.CharField(max_length=50)
    departamento =  forms.CharField(max_length=50)
    shortname = forms.CharField(max_length=20)
    
    class Meta:
        model = Departamento
        fields = (
            'name',
            'short_name',
            'anulate'
        )
        widgets = {
            'first_name' : forms.TextInput(
                attrs= {
                    'placeholder' : 'Nombres'
                }
            ) 
        }

    def clean_first_name(self):
        first_name = self.cleaned_data.get('first_name')
        
        if first_name.isdigit():
            raise forms.ValidationError('Solo se permiten letras')
        
        return first_name

employeeProyect/applications/departamento/views.py
from django.shortcuts import render
from django.views.generic.edit import (
    FormView
)
from django.views.generic import (
    ListView,
)

from .forms import DepartamentoForm

from .models import Departamento
from applications.persona.models import Empleado

# Create your views here.


class DepartamentoCreateView(FormView):
    form_class = DepartamentoForm
    template_name = "departamento/create_departamento.html"
    success_url = "persona/lista"

    def form_valid(self, form):

        departamento = Departamento(
            name=form.cleaned_data['departamento'],
            short_name=form.cleaned_data['shortname']
        )

        departamento.save()

        nombre = form.cleaned_data['nombre']
        apellido = form.cleaned_data['apellidos']
        Empleado.objects.create(
            first_name=nombre,
            last_name=apellido,
            job='1',
            departamento=departamento
        )
        return super(DepartamentoCreateView, self).form_valid(form)


class ListAllDepartamentos(ListView):
    template_name = 'departamento/list_all.html'
    model = Departamento
    context_object_name = 'departamentos'

employeeProyect/templates/departamento/create_departamento.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
Registrar Departamento
{% endblock title %}

{% block content %}

{% include 'includes/header.html' %}

<div class="grid-container">
    <div class="grid-x">
        <div class="cell">
            <h1>Registrar Departamento</h1>
        </div>
        <div class="cell">
            <form class="callout grid-x grid-margin-x" method="POST" enctype="multipart/form-data">{% csrf_token %}
                <div class="large-6 cell">
                    <label>Nombres:
                        {{form.nombre}}
                    </label>
                </div>
                <div class="large-6 cell">
                    <label>Apellidos:
                        {{form.apellidos}}
                    </label>
                </div>
                <div class="large-6 cell">
                    <label>Departamento:
                        {{form.departamento}}
                    </label>
                </div>
                <div class="large-6 cell">
                    <label>Short Name:
                        {{form.shortname}}
                    </label>
                </div>
                <div class="cell">
                    <button class="submit success button" type="submit">Crear Departamento</button>
                </div>
            </form>
        </div>

    </div>
</div>
{% endblock content %}

employeeProyect/templates/departamento/list_all.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
Lista departamentos
{% endblock title %}

{% block content %}
{% include 'includes/header.html' %}
<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Departamentos</h1>
        <table>
            <tbody>
                {%for departamento in departamentos%}
                <tr>
                    <td>{{departamento.name}}</td>
                    <td>{{departamento.short_name}}</td>
                    <td><a class="button warning" href="{% url 'persona_app:employees_by_area' shortname=departamento.short_name %}">Ver Empleados</a>
                    </td>
                </tr>
                {%endfor%}
            </tbody>
        </table>
        <!-- <div class="cell">
            {% if is_paginated %}
            <nav aria-label="Pagination">
                <ul class="pagination text-center">
                    {% if page_obj.has_previous %}
                    <li class="pagination-previous"><a href="?page={{ page_obj.previous_page_number }}"
                            aria-label="Previous page">Previous</a>
                    </li>
                    {% endif %}

                    {% for page in paginator.page_range %}

                    {% if page == page_obj.number %}
                    <li class="current"><span class="show-for-sr">You're on page</span><a href="?page={{ page }}"
                            aria-label="Page {{ page }}">{{ page }}</a></li>
                    {% else %}
                    <li><a href="?page={{ page }}" aria-label="Page {{ page }}">{{ page }}</a></li>
                    {% endif %}

                    {% endfor %}

                    {% if page_obj.has_next %}
                    <li class="pagination-next"><a href="?page={{ page_obj.next_page_number }}"
                            aria-label="Next page">Next</a></li>
                    {% endif %}
                </ul>
            </nav>
            {% endif %}
        </div> -->
    </div>
</div>
{% endblock content %}